apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      - name: myapp
        image: z2hx/appdemo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8501
